version: "3"

services:
    webserver:
        container_name: site-php
        build: 
            context: ./
            dockerfile: ./docker_site/dockerfile_site.yml
        environment: 
            XDEBUG_CONFIG: remote_host=host.docker.internal
            PHP_IDE_CONFIG: servername=localhost
        ports: 
        - 81:80
        volumes: 
        - ./web:/var/www/html/
        links: 
        - db
        depends_on:
        - db
        networks:
         - net


    db:
        container_name: mysql_site
        image: 'mysql:latest'
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
        - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: password 
            MYSQL_DATABASE: www_project
            MYSQL_USER: mysqluser 
            MYSQL_PASSWORD: mysqluser
        volumes:
        - ./docker_site/database:/var/lib/mysql   
        networks:
         - net
networks: 
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.220.0/24